LAb2/LAb2/Models/CalcModel.cs
using LAb2.Services;
namespace LAb2.Models
{
    public class CalcModel
    {
        public int a { get; set; }
        public int b { get; set; }
        public string operation { get; set; }
        public string? GetValue()
        {
            return CalcService.Operation(a, b, operation);
        }
    }
}

LAb2/LAb2/Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;
using LAb2.Services;
using LAb2.Models;
namespace LAb2.Controllers
{
    public class CalcController : Controller
    {
        public IActionResult Manual()
        {
            ViewData["Title"] = "Manual";
            if (Request.Method == "POST")
            {
                bool result;
                result = int.TryParse(HttpContext.Request.Form["a"], out int a);
                result = int.TryParse(HttpContext.Request.Form["b"], out int b);
                string op = HttpContext.Request.Form["operation"];
                ViewData["Result"] = CalcService.Operation(a, b, op);
                return View("Result");
            }
            return View("Form");
        }

        [HttpGet]
        [ActionName("ManualWithSeparateHandlers")]
        public IActionResult ManualWithSeparateHandlersGet()
        {
            ViewData["Title"] = "ManualWithSeparateHandlers";
            return View("Form");
        }

        [HttpPost]
        [ActionName("ManualWithSeparateHandlers")]
        public IActionResult ManualWithSeparateHandlersPost()
        {
            bool result;
            result = int.TryParse(HttpContext.Request.Form["a"], out int a);
            result = int.TryParse(HttpContext.Request.Form["b"], out int b);
            string op = HttpContext.Request.Form["operation"];
            ViewData["Result"] = CalcService.Operation(a, b, op);
            return View("Result");
        }
        
        [HttpGet]
        public IActionResult ModelBindingInParametrs()
        {
            ViewData["Title"] = "ModelBuildingInParameters";
            return View("Form");
        }
        [HttpPost]
        public IActionResult ModelBindingInParametrs(int a, string operation, int b)
        {
            ViewData["Title"] = "ModelBuildingInParameters";
            ViewData["Result"] = CalcService.Operation(a, b, operation);
            return View("Result");
        }

        [HttpGet]
        public IActionResult ModelBindingInSeparateModel()
        {
            ViewData["Title"] = "ModelBuildingInSeparateModel";
            return View("Form");
        }
        [HttpPost]
        public IActionResult ModelBindingInSeparateModel(CalcModel calcModel)
        {
            ViewData["Title"] = "ModelBuildingInSeparateModel";
            ViewData["Result"] = calcModel.GetValue();
            return View("Result");
        }
    }
}

LAb2/LAb2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LAb2.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

LAb2/LAb2/Views/Calc/Form.cshtml
<div class="text-left">
	<h1 class="display-4">@ViewData["Title"]</h1>
	@using (Html.BeginForm())
	{
		@Html.TextBox("a", "", new { type="number" })<br>
		@Html.DropDownList("operation", new SelectList(new[] {"+", "-", "*", "/"}))<br>
		@Html.TextBox("b", "", new { type="nubmer" })<br>
		<input type="submit" value="Submit" />
	}
</div>

LAb2/LAb2/Views/Calc/Result.cshtml
@{
	ViewData["Title"] = "Result";
}
<div class="text-left">
	<h1 class="display-4">Result</h1>
	<h2>@ViewData["Result"]</h2>
</div>

LAb2/LAb2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h1 class="display-4">Form parameters parsing demo</h1>
    <ul>
        <li><a asp-controller="Calc" asp-action="Manual">Manual parcing in single action</a></li>
        <li><a asp-controller="Calc" asp-action="ManualWithSeparateHandlers">Manual parcing in separate actions</a></li>
        <li><a asp-controller="Calc" asp-action="ModelBindingInParametrs">Model binding (parameters)</a></li>
        <li><a asp-controller="Calc" asp-action="ModelBindingInSeparateModel">Model binding (separate model)</a></li>
    </ul>
</div>

LAb2/LAb2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LAb2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LAb2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LAb2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LAb2
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>